<?php

/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/7/28
 * Time: 17:14
 */
class UItoTopWidget extends \yii\base\Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}